server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crs_bs_local
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
        connectionTimeout: 30000
        idleTimeout: 60000


file-storage:
  enabled: true
  mode: standalone

dromara:
  x-file-storage:
    default-platform: sftp-1 #默认使用的存储平台
      #    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    #对应平台的配置写在这里，注意缩进要对齐
    sftp:
      - platform: sftp-1
        enable-storage: true
        host: 124.71.212.167
        port: 9022
        user: crs_sftp
        password: r8I1bVcu%p_rbwqg
        base-path: upload/ # 存储基础路径
        domain: http://124.71.212.167:9022/
    ftp:
      - platform: ftp-1 # 存储平台标识
        enable-storage: true  # 启用存储
        host: localhost # 主机，例如：192.168.1.105
        port: 21 # 端口，默认21
        user: root # 用户名，默认 anonymous（匿名）
        password: root # 密码，默认空
        domain: ftp://localhost/ # 访问域名，注意“/”结尾，例如：ftp://192.168.1.105/
        base-path: config/ # 基础路径
        storage-path: /www/wwwroot/file.abc.com/ # 存储路径，可以配合 Nginx 实现访问，注意“/”结尾，默认“/”


